services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle123
      - ORACLE_DATABASE=XEPDB1
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
